Added windows + linux workflows test

diff --git a/.github/workflows/check-build-win.yml b/.github/workflows/check-build-win.yml
--- a/.github/workflows/check-build-win.yml
+++ b/.github/workflows/check-build-win.yml
@@ -7,6 +7,8 @@ on:
 jobs:
   test-windows:
     runs-on: windows-latest
+    env:
+      PYTHONUTF8: "1"
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -34,5 +36,4 @@ jobs:
         run: buddy modes
       - name: "[buddy] error on missing file"
         run: |
-          buddy doesnotexist.mp4
-          if ($LASTEXITCODE -eq 0) { exit 1 } else { echo "correctly errored" }
+          buddy doesnotexist.mp4; if ($LASTEXITCODE -ne 0) { echo "correctly errored"; exit 0 } else { exit 1 }
